---
# Check if Assessor Workbench is already installed in the expected place
- name: Check if Assessor Workbench is already installed
  ansible.builtin.stat:
    path: /opt/assessor-workbench
  register: assessorworkbench_directory

- name: Install Assessor Workbench
  when: not assessorworkbench_directory.stat.exists
  block:
    - name: Grab Assessor Workbench tarball from S3
      amazon.aws.aws_s3:
        bucket: "{{ assessor_workbench_bucket_name }}"
        object: "{{ assessor_workbench_tarball_object_name }}"
        dest: "/tmp/{{ assessor_workbench_tarball_object_name }}"
        mode: get
      become: no
      delegate_to: localhost

    - name: Copy the Assessor Workbench tarball
      ansible.builtin.copy:
        src: /tmp/{{ assessor_workbench_tarball_object_name }}
        dest: /tmp/{{ assessor_workbench_tarball_object_name }}
        mode: 0644

    - name: Delete local copy of Assessor Workbench tarball
      ansible.builtin.file:
        path: "/tmp/{{ assessor_workbench_tarball_object_name }}"
        state: absent
      become: no
      delegate_to: localhost

    - name: Extract the Assessor Workbench tarball
      ansible.builtin.unarchive:
        src: /tmp/{{ assessor_workbench_tarball_object_name }}
        dest: /opt
        remote_src: yes

    - name: Delete remote copy of Assessor Workbench tarball
      ansible.builtin.file:
        path: /tmp/{{ assessor_workbench_tarball_object_name }}
        state: absent
